-- TEST1 유저 삭제
--DROP USER TEST1 CASCADE;

-- TEST1 유저 생성 및 권한 부여
CREATE USER TEST1 IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE, DBA TO TEST1;

-- TS_TEST1 테이블스페이스 삭제
--DROP TABLESPACE TS_TEST1 INCLUDING CONTENTS AND DATAFILES;

-- TS_TEST1 테이블스페이스 생성
-- 맥OS(FREEPDB1을 도커로 띄운 경우)와, Enterprise 버전이 경로가 다르니 자신의 시스템에 맞게 경로 수정하세요.
CREATE TABLESPACE TS_TEST1 DATAFILE 'C:\APP\ORACLE\PRODUCT\21C\ORADATA\XE\XEPDB1\TS_TEST1_01.DBF' SIZE 10M AUTOEXTEND ON NEXT 10M;
ALTER TABLESPACE TS_TEST1 ADD DATAFILE 'C:\APP\ORACLE\PRODUCT\21C\ORADATA\XE\XEPDB1\TS_TEST1_02.DBF' SIZE 10M AUTOEXTEND ON NEXT 10M;

-- TEST1 유저의 기본 테이블스페이스를 앞에서 생성한 TS_TEST1으로 지정
ALTER USER TEST1 DEFAULT TABLESPACE TS_TEST1 QUOTA UNLIMITED ON TS_TEST1;

-- TEST1 유저의 기본 테이블스페이스를 시스템 기본 테이블스페이스인 USERS로 지정
--ALTER USER TEST1 DEFAULT TABLESPACE USERS;

-- 시스템 테이블스페이스 목록 확인
SELECT * FROM DBA_TABLESPACES;

-- 시스템 데이터파일 목록 확인
SELECT * FROM DBA_DATA_FILES;

-- 시스템 기본 문자셋 확인
SELECT * FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER IN ('NLS_CHARACTERSET', 'NLS_NCHAR_CHARACTERSET');
