-- 1일차 복습

-- 입력한 EMP(CLERK)들의 데이터를 조회
SELECT EMPNO, ENAME, DEPTNO, JOB
FROM EMP;

-- EMP(CLERK) 테이블의 직무 정보를 ALL과 DISTINCT 옵션으로 확인해본다.
SELECT ALL JOB
FROM EMP;

SELECT JOB
FROM EMP;

SELECT DISTINCT JOB
FROM EMP;

-- CLERK 테이블에 대한 전체 정보 조회
SELECT *
FROM EMP;

-- 칼럼에 ALIAS 사용
SELECT ENAME AS CLERK명, JOB AS 직무, HIREDATE AS 입사일
FROM EMP;

SELECT ENAME CLERK명, JOB 직무, HIREDATE 입사일
FROM EMP;

-- 이중 인용부호를 사용한 ALIAS
SELECT ENAME "CLERK 이름", JOB "직무", HIREDATE "입사 일자"
FROM EMP;

-- CLERK의 보너스를 급여의 300%로 산정한 결과를 조회한다.
SELECT ENAME 이름, SAL AS 급여, (SAL / 12 * 3) AS 보너스
FROM EMP;

-- <이름>의 급여는 $<급여>입니다.
SELECT ENAME||'의 급여은 $'||SAL||' 입니다.'
FROM EMP;

-- 문자형 함수
SELECT LOWER('SQL Expert') FROM DUAL;
SELECT UPPER('SQL Expert') FROM DUAL;
SELECT ASCII('A') FROM DUAL;
SELECT CHR(65) FROM DUAL;
SELECT CONCAT('RDBMS',' SQL') FROM DUAL;
SELECT SUBSTR('SQL Expert', 5, 3) FROM DUAL;
SELECT LENGTH('SQL Expert') FROM DUAL;
SELECT LTRIM('xxxYYZZxYZ','x') FROM DUAL;
SELECT RTRIM('XXYYzzXYzz','z') FROM DUAL;
SELECT TRIM('x' FROM 'xxYYZZxYZxx') FROM DUAL;
SELECT RTRIM('XXYYZZXYZ    ') FROM DUAL;

-- 숫자형 함수
SELECT ABS(-15) FROM DUAL;
SELECT SIGN(-20) FROM DUAL;
SELECT SIGN(0) FROM DUAL;
SELECT SIGN(+20) FROM DUAL;
SELECT MOD(7, 3) FROM DUAL;
SELECT CEIL(38.123) FROM DUAL;
SELECT CEIL(-38.123) FROM DUAL;
SELECT FLOOR(38.123) FROM DUAL;
SELECT FLOOR(-38.123) FROM DUAL;
SELECT ROUND(38.5235, 3) FROM DUAL;
SELECT ROUND(38.5235, 1) FROM DUAL;
SELECT ROUND(38.5235, 0) FROM DUAL;
SELECT ROUND(38.5235) FROM DUAL; -- 기본값은 0
SELECT TRUNC(38.5235, 3) FROM DUAL;
SELECT TRUNC(38.5235, 1) FROM DUAL;
SELECT TRUNC(38.5235, 0) FROM DUAL;
SELECT TRUNC(38.5235) FROM DUAL;

-- [Oracle] 날짜 산술연산
SELECT ENAME, (SYSDATE - HIREDATE)/7 WEEKS
FROM   EMP
WHERE  DEPTNO = 10;

-- CLERK(EMP) 테이블의 입사일자에서 년,월,일 데이터를 각각 출력한다.
SELECT ENAME
     , HIREDATE
     , EXTRACT(YEAR FROM HIREDATE) 입사년
     , EXTRACT(MONTH FROM HIREDATE) 입사월
     , EXTRACT(DAY FROM HIREDATE) 입사일
FROM EMP;

SELECT ENAME
     , HIREDATE
     , TO_CHAR(HIREDATE, 'YYYY') AS 입사년
     , TO_CHAR(HIREDATE, 'MM') AS 입사월
     , TO_CHAR(HIREDATE, 'DD') AS 입사일
FROM EMP;

---2일차 오전

-- 변환함수
SELECT CAST(123.45 AS VARCHAR(10))
     , CAST('123.56' AS NUMERIC)
     , CAST(1234.5678 AS DEC(7,3)) -- 전체자리는 7개 / 소수점은 3자리 고정
     , CAST(CURRENT_TIMESTAMP AS DATE)
FROM DUAL;

SELECT TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
     , TO_CHAR(1234.56, 'L9,999.99') --로컬 화폐 단위
     , TO_NUMBER('$12,345', '$99,999') -- 자리수가 다르면 오류남
     , TO_DATE('2014/03/01 21:30:18', 'YYYY/MM/DD HH24:MI:SS') AS "To_Date"
     , TO_TIMESTAMP('2014/03/01 21:30:18', 'YYYY/MM/DD HH24:MI:SS') AS "타임스탬프"
FROM DUAL;

-- [CASE] 표현
SELECT ENAME,
  CASE WHEN SAL > 2000
       THEN SAL
       ELSE 2000
  END AS REVISED_SAL
FROM EMP;

-- SIMPLE_CASE_EXPRESSION

SELECT LOC,
  CASE LOC
    WHEN 'NEW YORK' THEN 'EAST'
    WHEN 'BOSTON' THEN 'EAST'
    WHEN 'CHICAGO' THEN 'CENTER'
    WHEN 'DALLAS' THEN 'CENTER'
    ELSE 'ETC'
  END AS AREA
FROM DEPT;


-- SEARCHED_CASE_EXPRESSION

SELECT ENAME, 
  CASE WHEN SAL >= 2000 THEN 'HIGH'
       WHEN SAL >= 1000 THEN 'MID'
       ELSE 'LOW'
  END AS SAL_GRADE
FROM EMP;

-- CASE의 중첩

SELECT ENAME, SAL,
  CASE WHEN SAL >= 2000
       THEN 1500
       ELSE (CASE WHEN SAL >= 1000
                  THEN 1000
                  ELSE SAL * 0.5
             END)
  END AS BONUS
FROM EMP;

-- [NULL] 
-- CLERK 테이블에서 CLERK이름과 직무를 출력하는데, 직무가 없는 경우는 'None'으로 표시한다.

--------------------------------
--- 테스트를 위해 특정값만 NULL로 변경
UPDATE EMP SET JOB = NULL WHERE EMPNO = 7934; -- '' = NULL

-----비교
SELECT EMPNO, coalesce(mgr, -1) AS RESULT
FROM emp;

SELECT EMPNO, nvl(mgr, -1) AS RESULT
FROM emp;

SELECT EMPNO, coalesce(mgr, '-1') AS RESULT -- 오류 : 타입이 같아야 함
FROM emp;

SELECT EMPNO, nvl(mgr, '-1') AS RESULT
FROM emp;

SELECT EMPNO, nvl2(job, job, -1) AS RESULT
FROM emp;

SELECT EMPNO, nvl2(job, job, '-1') AS RESULT
FROM emp;
------

SELECT ENAME, JOB,  
       NVL(JOB, 'None') 직무1, COALESCE(JOB, 'None') 직무2
FROM EMP;

SELECT ENAME, JOB, 
  CASE WHEN JOB IS NULL
       THEN 'None'
       ELSE JOB
  END AS 직무
FROM EMP;

-- 원래의 값으로 복원
UPDATE EMP SET JOB = 'CLERK' WHERE EMPNO = 7934;
----------------------------------------------------------

-- 실행결과가 NULL

SELECT MGR FROM EMP 
WHERE ENAME = 'KING'; -- Null 이면 null 이 출력

-- 실행결과 공집합

SELECT MGR FROM EMP 
WHERE ENAME = 'JSC'; -- 공집합이라 없으면 공백 출력

-- 공집합에 대한 NVL

SELECT NVL(SAL, 0) SAL FROM EMP WHERE ENAME = 'JSC';

-- 공집합에 대한 집계함수

SELECT MAX(SAL) SAL FROM EMP WHERE ENAME='JSC';
SELECT MIN(SAL) SAL FROM EMP WHERE ENAME='JSC';

-- 공집합의 올바른 NULL 처리

SELECT NVL(MAX(SAL), 9999) SAL
FROM EMP 
WHERE ENAME='JSC';

-----Nvl 연습
SELECT * FROM emp;
SELECT count(comm), count(nvl(comm, -1)) FROM emp;
SELECT count(comm), count(NVL(TO_CHAR(comm), 'None')) FROM emp; -- 동일함


---2일차 오후

--where 절

-- 문자형 값 비교

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무, SAL 급여  
FROM   EMP
WHERE  JOB = 'MANAGER' OR job = 'CLERK'; --대소문자 구분

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무, SAL 급여  
FROM   EMP
WHERE  JOB IN ('CLERK', 'MANAGER'); --대소문자 구분

-- 숫자 비교

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무, SAL 급여  
FROM   EMP 
WHERE  SAL >= 1000 AND sal <= 2000;

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무, SAL 급여  
FROM   EMP 
WHERE  SAL BETWEEN 1000 AND 2000;

-- WHERE절 연산자 우선순위

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무, SAL 급여
FROM   EMP
WHERE (DEPTNO = '10' OR DEPTNO = '20' OR DEPTNO = '30')
AND    JOB = 'CLERK'
AND    SAL >= 1000
AND    SAL <= 2000;

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무, SAL 급여
FROM   EMP
WHERE  DEPTNO IN ('10', '20', '30')
AND    JOB = 'CLERK'
AND    SAL BETWEEN 1000 AND 2000;

-- 다중 적용 (A,B)이 튜플임

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무, SAL 급여
FROM   EMP
WHERE (DEPTNO, JOB) IN (('10', 'CLERK'), ('20', 'CLERK'), ('30', 'CLERK'))
  AND SAL BETWEEN 1000 AND 2000;

-- BETWEEN

SELECT ENAME CLERK이름, SAL 급여  
FROM   EMP
WHERE  SAL BETWEEN 1000 AND 2000;

-- IN

SELECT ENAME, DEPTNO, JOB
FROM   EMP
WHERE  DEPTNO IN ('10','20')
AND    JOB IN ('MANAGER','PRESIDENT');

SELECT ENAME, DEPTNO, JOB
FROM   EMP
WHERE (DEPTNO, JOB) IN
      (('20','MANAGER'), ('10','PRESIDENT'));

-- 'S'로 시작하는 이름을 가진 직원들의 정보를 조회

SELECT ENAME 이름, DEPTNO 팀코드, JOB 직무, HIREDATE 입사일자
FROM   EMP
WHERE  ENAME LIKE 'S%';

-- 이름의 두 번째 글자가 'A'인 임직원의 정보를 조회

SELECT ENAME 이름, DEPTNO 팀코드, JOB 직무, HIREDATE 입사일자
FROM   EMP
WHERE  ENAME LIKE '_A%';

-- 이름의 A가 들어가있는 직원 조회
SELECT ENAME 이름, DEPTNO 팀코드, JOB 직무, HIREDATE 입사일자
FROM   EMP
WHERE  ENAME LIKE '%A%';

SELECT ENAME 이름, DEPTNO 팀코드, JOB 직무, HIREDATE 입사일자
FROM   EMP
WHERE  ENAME LIKE '_A____';

SELECT count(*)
FROM   EMP
WHERE  ENAME LIKE '__A____';

-- IS NULL

SELECT ENAME 이름, DEPTNO 소속, JOB 직무, COMM 커미션 
FROM   EMP
WHERE  COMM = NULL;

SELECT ENAME 이름, DEPTNO 소속, JOB 직무, COMM 커미션 
FROM   EMP
WHERE  COMM IS NULL;

SELECT empno, ename
FROM emp
WHERE comm IN (NULL, 300, 500);
-- = not (comm = NULL OR Comm = 300 OR comm = 500)
-- = comm <> NULL AND COMM <> 300 AND COMM <> 500

--  NOT

SELECT  ENAME CLERK이름, DEPTNO 소속, JOB 직무
FROM    EMP
WHERE   DEPTNO = '20'
AND NOT JOB = 'MANAGER';

-- IS NOT NULL

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무
FROM   EMP
WHERE  MGR IS NOT NULL;

-- ROWNUM

SELECT ENAME CLERK이름, DEPTNO 소속, JOB 직무
FROM   EMP
WHERE  DEPTNO IS NOT NULL
   AND ROWNUM <= 10;

-- GROUP BY

SELECT   JOB "직무"
       , COUNT(*) "인원수"
       , MIN(SAL) "최소 급여"
       , MAX(SAL) "최대 급여"
       , AVG(SAL) "평균 급여"
FROM     EMP
GROUP BY JOB;


-- GROUP BY 일반 그룹핑

SELECT DEPTNO, JOB, AVG( SAL) "평균 급여"
FROM   EMP
WHERE  JOB IN ('CLERK', 'MANAGER', 'ANALYST')
GROUP  BY DEPTNO, JOB;

-- CASE + GROUP BY

SELECT DEPTNO
     , AVG(CASE JOB WHEN 'SALESMAN' THEN SAL END) "SALESMAN 평균" 
     , AVG(CASE JOB WHEN 'MANAGER' THEN SAL END) "MANAGER 평균" 
     , AVG(CASE JOB WHEN 'CLERK' THEN SAL END) "CLERK 평균"
FROM   EMP
WHERE  JOB IN ('CLERK', 'MANAGER', 'SALESMAN')
GROUP  BY DEPTNO;

-- 집계 함수

SELECT COUNT(*) "전체건수"
     , COUNT(JOB) "직무건수"
     , COUNT(DISTINCT JOB) "직무종류"
     , MAX(SAL) "최대"
     , MIN(SAL) "최소"
     , AVG(SAL) "평균" 
FROM EMP;

DROP TABLE TBL;
CREATE TABLE TBL(C1 NUMBER, C2 NUMBER, C3 NUMBER);
INSERT INTO TBL VALUES (10, 20, NULL);
INSERT INTO TBL VALUES (NULL, 20, 30);

SELECT C1+C2+C3 FROM tbl;
SELECT SUM(C1+C1) FROM tbl;
SELECT SUM(C1)+SUM(C2)+SUM(C3) FROM tbl;

-- 개선 전 SQL (SIMPLE_CASE_EXPRESSION)

SELECT DEPTNO,
       SUM(COALESCE((CASE JOB WHEN 'MANAGER' THEN 1 ELSE 0 END),0)) "MANAGER",
       SUM(COALESCE((CASE JOB WHEN 'ALALYST' THEN 1 ELSE 0 END),0)) "ALALYST",
       SUM(COALESCE((CASE JOB WHEN 'SALESMAN' THEN 1 ELSE 0 END),0)) "SALESMAN",
       SUM(COALESCE((CASE JOB WHEN 'CLERK' THEN 1 ELSE 0 END),0)) "CLERK"
FROM   EMP
GROUP  BY DEPTNO;

-- 개선 후 SQL (SIMPLE_CASE_EXPRESSION)

SELECT DEPTNO,
       COALESCE(SUM(CASE JOB WHEN 'MANAGER' THEN 1 END),0) "MANAGER",
       COALESCE(SUM(CASE JOB WHEN 'ALALYST' THEN 1 END),0) "ALALYST",
       COALESCE(SUM(CASE JOB WHEN 'SALESMAN' THEN 1 END),0) "SALESMAN",
       COALESCE(SUM(CASE JOB WHEN 'CLERK' THEN 1 END),0) "CLERK"
FROM   EMP
GROUP  BY DEPTNO;

-- HAVING 1

SELECT DEPTNO "부서", COUNT(*) "인원수", AVG(SAL) "평균"
FROM   EMP
GROUP  BY DEPTNO
HAVING COUNT(*) >= 4;

-- HAVING 2

SELECT DEPTNO "부서", MAX(SAL) "최대" 
FROM   EMP 
GROUP  BY DEPTNO 
HAVING MIN(SAL) <= 40000000;

-- ORDER BY

SELECT DEPTNO 부서, ENAME 사원이름, HIREDATE 입사일
FROM   EMP
ORDER  BY DEPTNO, HIREDATE DESC;

SELECT ENAME, EMPNO, DEPTNO
FROM   EMP
ORDER  BY ENAME ASC, EMPNO ASC, DEPTNO DESC;

SELECT ENAME NAME, EMPNO NO
     , DEPTNO ORG
FROM   EMP
ORDER  BY NAME, NO, ORG DESC;

SELECT ENAME, EMPNO, DEPTNO
FROM   EMP
ORDER  BY 1 ASC, 2 ASC, 3 DESC;

SELECT ENAME NAME, EMPNO NO
     , DEPTNO ORG
FROM   EMP
ORDER  BY ENAME, 2, ORG DESC;
