-- 8장 JOIN ~ 9장 서브쿼리 

-- 오전

SELECT EMP.ENAME
     , EMP.DEPTNO
     , DEPT.DEPTNO
     , DEPT.DNAME
FROM   EMP, DEPT
WHERE  EMP.DEPTNO = DEPT.DEPTNO;

SELECT EMP.EMPNO, EMP.ENAME, EMP.DEPTNO
     , DEPT.DNAME, EMP.JOB
FROM   EMP, DEPT
WHERE  EMP.DEPTNO = DEPT.DEPTNO;

SELECT E.EMPNO, E.ENAME, E.DEPTNO
     , O.DNAME, E.JOB
FROM   EMP E, DEPT O
WHERE  E.DEPTNO = O.DEPTNO;

SELECT E.EMPNO, E.ENAME, E.DEPTNO
     , O.DNAME, E.JOB
FROM   EMP E, DEPT O
WHERE  E.DEPTNO = O.DEPTNO
AND    E.JOB = 'MANAGER'
ORDER BY O.DNAME;

SELECT EMP.EMPNO, EMP.ENAME, EMP.DEPTNO
     , DEPT.DNAME, EMP.JOB
FROM   EMP, DEPT
WHERE  EMP.DEPTNO = DEPT.DEPTNO;

SELECT E.EMPNO, E.ENAME, E.DEPTNO
     , O.DNAME, E.JOB
FROM   EMP E, DEPT O
WHERE  E.DEPTNO = O.DEPTNO;

-- AS 적용안해도 되는 건 고유 속성일 경우

SELECT EMPNO, ENAME, E.DEPTNO
     , DNAME, JOB
FROM   EMP E, DEPT O
WHERE  E.DEPTNO = O.DEPTNO;

--------------

SELECT * FROM salgrade;

--- Non equi join
SELECT E.ENAME 사원명, E.SAL 급여, S.GRADE 급여레벨
FROM   EMP E, SALGRADE S
WHERE  E.SAL  BETWEEN  S.LOSAL AND S.HISAL;

SELECT EMP.EMPNO, EMP.ENAME, ORG.DNAME
FROM   EMP EMP, DEPT ORG
WHERE  EMP.DEPTNO = ORG.DEPTNO;

--- Inner join
SELECT EMP.EMPNO, EMP.ENAME, DEPT.DNAME
FROM   EMP INNER JOIN DEPT
  ON   EMP.DEPTNO = DEPT.DEPTNO;

SELECT EMP.EMPNO, EMP.ENAME, ORG.DNAME
FROM   EMP EMP JOIN DEPT ORG
  ON   EMP.DEPTNO = ORG.DEPTNO;

SELECT E.EMPNO, D.DEPTNO, D.DNAME
FROM   EMP E INNER JOIN DEPT D 
  ON  (E.DEPTNO = D.DEPTNO);

SELECT E.ENAME, E.DEPTNO, O.DEPTNO, O.DNAME
FROM   EMP E JOIN DEPT O
  ON  (E.DEPTNO = O.DEPTNO)
WHERE  E.DEPTNO = '10';

--- Cross Join
SELECT E.ENAME, O.DNAME
FROM   EMP E, DEPT O
ORDER  BY ENAME;

SELECT E.ENAME, O.DNAME
FROM   EMP E CROSS JOIN DEPT O
ORDER  BY ENAME;

SELECT E.ENAME, O.DNAME
FROM   EMP E NATURAL JOIN DEPT O;

--- 오후 ---
--- 표준 JOIN ---
SELECT E.EMPNO 사번, E.ENAME 사원명
     , E.JOB 직무, O.DNAME 부서명
FROM   EMP E LEFT OUTER JOIN DEPT O
       ON E.DEPTNO = O.DEPTNO
WHERE  E.JOB = 'CLERK';

SELECT E.EMPNO 사번, E.ENAME 사원명, E.JOB 직책, O.DNAME 부서명
FROM   DEPT O RIGHT OUTER JOIN EMP E
       ON E.DEPTNO = O.DEPTNO
WHERE  E.JOB = 'CLERK';

SELECT A.DEPTNO, A.DNAME, B.DEPTNO, B.DNAME 
FROM DEPT A FULL OUTER JOIN DEPT B
     ON A.DEPTNO = B.DEPTNO;

SELECT A.DEPTNO, A.DNAME, B.DEPTNO, B.DNAME
FROM   DEPT A LEFT OUTER JOIN DEPT B
       ON A.DEPTNO = B.DEPTNO
UNION
SELECT A.DEPTNO, A.DNAME, B.DEPTNO, B.DNAME
FROM   DEPT A RIGHT OUTER JOIN DEPT B
       ON A.DEPTNO = B.DEPTNO;

-- 서브쿼리

-- 스칼라 서브쿼리
SELECT E.EMPNO,
       E.ENAME,
      (SELECT D.DNAME
       FROM DEPT D
       WHERE D.DEPTNO = E.DEPTNO) AS DNAME
FROM EMP E;

----인라인 뷰
SELECT E.EMPNO,
       E.ENAME,
       D.DEPTNO,
       D.DNAME,
       D.LOC
FROM EMP E,
    (SELECT DEPTNO,
            DNAME,
            LOC
     FROM DEPT) D
WHERE E.DEPTNO = D.DEPTNO;

---- 인라인 뷰 생성
CREATE OR REPLACE VIEW V_EMP AS
SELECT EMPNO,
       ENAME,
       SAL,
       E.DEPTNO,
       D.DNAME,
       D.LOC
FROM EMP E LEFT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

SELECT * FROM V_EMP;

DROP VIEW V_EMP;

-----------------
-- 중첩 서브쿼리 --
----단일행 서브쿼리
SELECT EMPNO,
       ENAME,
       SAL
FROM EMP
WHERE SAL >= (SELECT AVG(E.SAL) FROM EMP E);

----다중행 서브쿼리
SELECT EMPNO,
       ENAME,
       SAL,
       DEPTNO
FROM EMP
WHERE DEPTNO IN (SELECT DISTINCT DEPTNO
                 FROM EMP
                 WHERE SAL <= 1000);
---다중컬럼 중첩 서브쿼리 
SELECT EMPNO,
       ENAME,
       JOB,
       SAL
FROM EMP
WHERE (JOB, SAL) IN (SELECT JOB, MAX(SAL)
                     FROM EMP
                     GROUP BY JOB);

----고급 쿼리 ----
-- 쿼리 적용을 위한 MTCARS 테이블 만들기

--CREATE TABLE MTCARS
--(
--    NAME    VARCHAR2(50), 
--    MPG     NUMBER,
--    CYL     NUMBER,
--    HP      NUMBER,
--    GEAR    NUMBER
--);

--INSERT INTO MTCARS VALUES('Mazda RX4', 21, 6, 110, 4);
--INSERT INTO MTCARS VALUES('Mazda RX4 Wag', 21, 6, 110, 4);
--INSERT INTO MTCARS VALUES('Datsun 710', 23, 4, 93, 4);
--INSERT INTO MTCARS VALUES('Hornet 4 Drive', 21, 6, 110, 3);
--INSERT INTO MTCARS VALUES('Hornet Sportabout', 19, 8, 175, 3);
--INSERT INTO MTCARS VALUES('Valiant', 18, 6, 105, 3);
--INSERT INTO MTCARS VALUES('Duster 360', 14, 8, 245, 3);
--INSERT INTO MTCARS VALUES('Merc 240D', 24, 4, 62, 4);
--INSERT INTO MTCARS VALUES('Merc 230', 23, 4, 95, 4);
--INSERT INTO MTCARS VALUES('Merc 280', 19, 6, 123, 4);
--INSERT INTO MTCARS VALUES('Merc 280C', 18, 6, 123, 4);
--INSERT INTO MTCARS VALUES('Merc 450SE', 16, 8, 180, 3);
--INSERT INTO MTCARS VALUES('Merc 450SL', 17, 8, 180, 3);
--INSERT INTO MTCARS VALUES('Merc 450SLC', 15, 8, 180, 3);
--INSERT INTO MTCARS VALUES('Cadillac Fleetwood', 10, 8, 205, 3);
--INSERT INTO MTCARS VALUES('Lincoln Continental', 10, 8, 215, 3);
--INSERT INTO MTCARS VALUES('Chrysler Imperial', 15, 8, 230, 3);
--INSERT INTO MTCARS VALUES('Fiat 128', 32, 4, 66, 4);
--INSERT INTO MTCARS VALUES('Honda Civic', 30, 4, 52, 4);
--INSERT INTO MTCARS VALUES('Toyota Corolla', 34, 4, 65, 4);
--INSERT INTO MTCARS VALUES('Toyota Corona', 22, 4, 97, 3);
--INSERT INTO MTCARS VALUES('Dodge Challenger', 16, 8, 150, 3);
--INSERT INTO MTCARS VALUES('AMC Javelin', 15, 8, 150, 3);
--INSERT INTO MTCARS VALUES('Camaro Z28', 13, 8, 245, 3);
--INSERT INTO MTCARS VALUES('Pontiac Firebird', 19, 8, 175, 3);
--INSERT INTO MTCARS VALUES('Fiat X1-9', 27, 4, 66, 4);
--INSERT INTO MTCARS VALUES('Porsche 914-2', 26, 4, 91, 5);
--INSERT INTO MTCARS VALUES('Lotus Europa', 30, 4, 113, 5);
--INSERT INTO MTCARS VALUES('Ford Pantera L', 16, 8, 264, 5);
--INSERT INTO MTCARS VALUES('Ferrari Dino', 20, 6, 175, 5);
--INSERT INTO MTCARS VALUES('Maserati Bora', 15, 8, 335, 5);
--INSERT INTO MTCARS VALUES('Volvo 142E', 21, 4, 109, 4);
-----------------

---윈도우 함수
----순위 함수
SELECT MPG,
       COUNT(*),
       RANK() OVER(ORDER BY COUNT(*) DESC) AS RANK
FROM MTCARS
GROUP BY MPG;

-- 집계함수
SELECT NAME,
       CYL,
       COUNT(*) OVER(PARTITION BY CYL) AS PART_CYL_CNT
FROM MTCARS
WHERE CYL <= 6;

SELECT NAME,
       CYL,
       MPG,
       MAX(MPG) OVER(PARTITION BY CYL) AS PART_MAX_MPG
FROM MTCARS
WHERE CYL <= 6;

-- 행 순서 함수
SELECT NAME,
       CYL,
       MPG,
       FIRST_VALUE(MPG) OVER(PARTITION BY CYL) AS PART_FIRST_MPG
FROM MTCARS
WHERE CYL <= 6;

SELECT NAME,
       CYL,
       MPG,
       LAG(MPG, 2) OVER(ORDER BY MPG) AS MPG_2
FROM MTCARS
WHERE CYL <= 6;

-- 비율 함수
SELECT NAME,
       CYL,
       MPG,
       CUME_DIST() OVER(ORDER BY MPG) AS C_DIST,
       PERCENT_RANK() OVER(ORDER BY MPG) AS P_RANK,
       NTILE(5) OVER(ORDER BY MPG) AS N_TILE,
       RATIO_TO_REPORT(MPG) OVER(PARTITION BY CYL) AS R_REPORT
FROM MTCARS
WHERE CYL <= 6;